spring:
  application:
    name: user-service
  profiles:
    active: postgresql
  cloud:
    config:
      uri: http://localhost:8888
      label: main
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

security:
  jwt:
    token:
      secret-key: null