spring:
  profiles:
    active: postgresql
  application:
    name: users-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 9090
  servlet:
    context-path: /api/