server.port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/earlspilner/the-github-times-config-properties.git
