spring:
  application:
    name: the-github-times
  datasource:
    url: jdbc:postgresql://localhost:5432/the-github-times
    driverClassName: org.postgresql.Driver
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: secret

logging:
  level:
    root: info
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"