spring:
  application:
    name: security-security
  datasource:
    url: jdbc:postgresql://localhost:5432/the-github-times
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 7654
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: