server:
  port: 9001

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/newspaper-user-service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  application:
    name: auth-service

jwt:
  secret: [ SECRET-KEY ]
  expiration: 86400
