server:
  port: 9002

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/newspaper-user-service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

