spring:
#  cloud:
#    gateway:
#      routes:
#        - id: authentication-server
#          uri: http://localhost:6969
#          predicates:
#            - Path=/api/auth/**
#
#        - id: users-service
#          uri: http://localhost:9090
#          predicates:
#            - Path=/api/users/**
#
#        - id: profiles-service
#          uri: http://localhost:9091
#          predicates:
#            - Path=/api/profiles/**
#
#        - id: articles-service
#          uri: http://localhost:9093
#          predicates:
#            - Path=/api/articles/**, /api/categories/**, /api/tags/**
  application:
    name: api-gateway
