spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/users/**

        - id: authentication-service
          uri: http://localhost:8989
          predicates:
            - Path=/api/auth/**

server:
  port: 8080