spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 9090

security:
  jwt:
    token:
      secret-key: null # Use KeyGenerator.java
      accessExpiration: 300000   # 5 minutes duration by default
      refreshExpiration: 3600000 # 60 minutes duration by default