server:
  port: 9297

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/earlspilner/demo-config-server.git
          clone-on-start: true
          default-label: master