server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/earlspilner/demo-config-server
          clone-on-start: true
          default-label: master